CREATE TABLE PUBLIC.SERVICE (
	ID INTEGER NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT SERVICE_PK PRIMARY KEY (ID)
);
CREATE TABLE PUBLIC.CITY (
	ID INTEGER NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	CONSTRAINT CITY_PK PRIMARY KEY (ID)
);
CREATE TABLE PUBLIC.SERVICE_CITY (
	SERVICE_ID INTEGER NOT NULL,
	CITY_ID INTEGER NOT NULL,
	URL VARCHAR(1000),
	CONSTRAINT SERVICE_CITY_PK PRIMARY KEY (SERVICE_ID,CITY_ID),
	CONSTRAINT SERVICE_CITY_FK FOREIGN KEY (SERVICE_ID) REFERENCES PUBLIC.SERVICE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT SERVICE_CITY_FK_1 FOREIGN KEY (CITY_ID) REFERENCES PUBLIC.CITY(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);